language: python
python:
  - "2.6"
  - "2.7"
addons:
  postgresql: "9.3"
env:
- DATABASE_URL=postgres://postgres@127.0.0.1:5432/test_nextbeer

# command to install dependencies
install:
  - pip install --quiet -r requirements.txt

# command to
before_script:
  - psql -c 'create database test_nextbeer;' -U postgres
  - psql -a -U postgres -d test_nextbeer -f resetTables.sql

# command to run tests
script: nosetests specs/test.py -v

# Whitelisting example
branches:
  only:
    - master
